version: 2

builds:
  - main: .
    binary: cubit
    ldflags:
      - -s -w
      - -X github.com/SeanoChang/cubit/cmd.Version={{.Version}}
      - -X github.com/SeanoChang/cubit/cmd.Commit={{.ShortCommit}}
      - -X github.com/SeanoChang/cubit/cmd.Date={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: amd64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
